export const SURAT = {
  canvasBg: '#f0eee9',
  popupBg: '#faf9f5',
  card: '#ffffff',
  cardAlt: '#f5f2ea',
  ink: '#2a251f',
  ink2: '#6b6358',
  ink3: '#9c9489',
  accent: '#c15f3c',
  accentInk: '#7a3618',
  accentSoft: '#f4e6dd',
  border: '#e8e2d6',
  borderStrong: '#d6cebd',
  success: '#5b7c4a',
  successSoft: '#e8efe1',
  warning: '#b8893d',
  warningSoft: '#f5ecd9',
  danger: '#a8463a',
  serif: 'var(--font-source-serif-4), "Source Serif Pro", Iowan, "Times New Roman", serif',
  sans: 'var(--font-inter), "Helvetica Neue", Helvetica, system-ui, sans-serif',
  mono: 'var(--font-jetbrains-mono), "SF Mono", ui-monospace, Menlo, monospace',
} as const;
